spring:
  application:
    name: mySink_routing_sinkBased
  cloud:
    stream:
      bindings:
        input:
          destination: output
          group: processQueue
        output:
          destination: output
          producer:
            requiredGroup: acknowledgeQueue